/// Structured AI incident intelligence and responder guidance metadata for Pukaar.
class AIIntelligence {
  /// Concise, objective emergency triage summary.
  final String summary;

  /// Urgency rating: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'.
  final String urgencyScore;

  /// Extracted hazard warnings or risk factors.
  final List<String> hazards;

  /// Conservative, SOP-oriented responder guidance checklist.
  final List<String> recommendedActions;

  /// Key information gaps (e.g. unknown consciousness, missing floor number).
  final List<String> missingInfo;

  /// Intelligence source: 'rule_based' or 'llm'.
  final String source;

  /// Confidence score between 0.0 and 1.0.
  final double confidence;

  /// Timestamp when intelligence was generated.
  final DateTime? generatedAt;

  const AIIntelligence({
    required this.summary,
    required this.urgencyScore,
    this.hazards = const [],
    this.recommendedActions = const [],
    this.missingInfo = const [],
    this.source = 'rule_based',
    this.confidence = 0.5,
    this.generatedAt,
  });

  /// True if intelligence was generated by external LLM enrichment.
  bool get isLlm => source.toLowerCase() == 'llm';

  /// Deserializes safely from JSON map with fallback defaults.
  factory AIIntelligence.fromJson(Map<String, dynamic> json) {
    return AIIntelligence(
      summary: json['summary'] as String? ?? '',
      urgencyScore: (json['urgencyScore'] as String? ?? 'HIGH').toUpperCase(),
      hazards: (json['hazards'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .where((e) => e.isNotEmpty)
              .toList() ??
          const [],
      recommendedActions: (json['recommendedActions'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .where((e) => e.isNotEmpty)
              .toList() ??
          const [],
      missingInfo: (json['missingInfo'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .where((e) => e.isNotEmpty)
              .toList() ??
          const [],
      source: json['source'] as String? ?? 'rule_based',
      confidence: (json['confidence'] as num?)?.toDouble() ?? 0.5,
      generatedAt: json['generatedAt'] != null
          ? DateTime.tryParse(json['generatedAt'] as String)
          : null,
    );
  }

  /// Serializes to JSON map.
  Map<String, dynamic> toJson() {
    return {
      'summary': summary,
      'urgencyScore': urgencyScore,
      'hazards': hazards,
      'recommendedActions': recommendedActions,
      'missingInfo': missingInfo,
      'source': source,
      'confidence': confidence,
      'generatedAt': generatedAt?.toIso8601String(),
    };
  }

  /// Creates a copy with specified fields replaced.
  AIIntelligence copyWith({
    String? summary,
    String? urgencyScore,
    List<String>? hazards,
    List<String>? recommendedActions,
    List<String>? missingInfo,
    String? source,
    double? confidence,
    DateTime? generatedAt,
  }) {
    return AIIntelligence(
      summary: summary ?? this.summary,
      urgencyScore: urgencyScore ?? this.urgencyScore,
      hazards: hazards ?? this.hazards,
      recommendedActions: recommendedActions ?? this.recommendedActions,
      missingInfo: missingInfo ?? this.missingInfo,
      source: source ?? this.source,
      confidence: confidence ?? this.confidence,
      generatedAt: generatedAt ?? this.generatedAt,
    );
  }

  @override
  String toString() {
    return 'AIIntelligence(urgency: $urgencyScore, source: $source, confidence: $confidence, summary: $summary)';
  }
}
